[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run dev"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend" 